### ISSUE TITLE
Extra attributes from the server: tabindex

### ISSUE THREAD

**Issue by GoudekettingRM** [rpearce/react-medium-image-zoom#282]
This issue is a: 

- Bug report

I am using react-medium-image-zoom in my NextJs app and on page load I get an error in the console; `Extra attributes from the server: tabindex`. It seems to have something to do with the scroll transition in your package, but I'm not entirely sure. The stacktrace below for extra information. 

Any help or insight greatly appreciated. Note, the package works as intended as far as I can tell, but the big red error is just not very nice. It could also be that I am doing something wrong elsewhere. 

## Expected behavior
I expected no error

## Actual behavior
What actually happened was an error

## Steps to reproduce behavior
I tried to make a code sandbox, but they don't allow to install with legacy peer deps, and hence only v3 works there. I am running next 10.0.7, react 17.0.1, and react-medium-image-zoon 4.3.1.

## Stack trace
```
react-dom.development.js?61bb:67 Warning: Extra attributes from the server: tabindex
    at button
    at div
    at Uncontrolled (webpack-internal:///./node_modules/react-medium-image-zoom/dist/esm/index.js:109:23)
    at li
    at ul
    at ScrollTransition (webpack-internal:///./node_modules/nuka-carousel/es/transitions/scroll-transition.js:48:5)
    at NodeGroup (webpack-internal:///./node_modules/react-move/NodeGroup/index.js:58:5)
    at Animate (webpack-internal:///./node_modules/react-move/Animate/index.js:54:5)
    at div
    at div
    at Carousel (webpack-internal:///./node_modules/nuka-carousel/es/index.js:89:5)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19542)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19542)
    at div
    at article
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19542)
    at ImageCarouselArticle (webpack-internal:///./components/Portfolio/PortfolioImageWithCarousel.tsx:25:20)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19542)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19542)
    at PageContentLayout (webpack-internal:///./ui/Page/PageContentLayout.tsx:16:20)
    at section
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19542)
    at VisualRecordings (webpack-internal:///./pages/visual-recordings.tsx:39:129)
    at main
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:19542)
    at AppLayout (webpack-internal:///./Layouts/AppLayout.tsx:25:23)
    at MessagesContextProvider (webpack-internal:///./contexts/messagesContext/MessagesContextProvider.tsx:21:23)
    at Ge (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:28:17052)
    at MyApp (webpack-internal:///./pages/_app.tsx:28:24)
    at ErrorBoundary (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ErrorBoundary.js:23:47)
    at ReactDevOverlay (webpack-internal:///./node_modules/@next/react-dev-overlay/lib/internal/ReactDevOverlay.js:73:23)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:184:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:672:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:803:24)
```

**Comment by rpearce** [comment]
Hi! Thanks for using this project and opening this issue with a lot of useful info.

As I've still never used nextjs before, it would be _super_ helpful if you had a demo project that I could take a look at that reproduces the issue.

Thanks for your patience, and I'll see if I can get you sorted ASAP.

**Comment by rpearce** [comment]
There's a general update here, https://github.com/rpearce/image-zoom/discussions/274#discussioncomment-1616865, but when doing server-side rendering, these components are going to render their children and only load in the browser-based interactive bits when it actually gets into a browser environment.

**Comment by rpearce** [comment]
@GoudekettingRM You should be able to use `v4.4.0` in codesandbox now to provide an example.

**Comment by rpearce** [comment]
Hi, @GoudekettingRM. This issue has been here a while, but if you happen to still be using this library and find some spare time and wants to give the latest build a whirl to try out the fix:

```sh
npm i --save react-medium-image-zoom@5.0.0-beta2.6
```

And, if you aren't already,

```jsx
import Zoom from 'react-medium-image-zoom'
import 'react-medium-image-zoom/dist/styles.css'

// ... your other code

<Zoom>
  <MyImage />
</Zoom>
```

The updated [`v5-dev` README is here](https://github.com/rpearce/react-medium-image-zoom/tree/v5-dev#react-medium-image-zoom), and there are some breaking changes to the extra options passed to be aware of, if you're using the options.

Thanks for your time!

**Comment by GoudekettingRM** [comment]
Hi @rpearce 

I am still using it, just haven't touched the project in a while haha, it's been steady and working fine, the error doesn't completely break it 🤷 

I will give it a whirl later on, and let you know!

Thanks for updating me (:

**Comment by rpearce** [comment]
Should be closed now via https://github.com/rpearce/react-medium-image-zoom/pull/329
