### ISSUE TITLE
An error occurred in this module while using Jest.

### ISSUE THREAD

**Issue by amkkr** [rpearce/react-medium-image-zoom#425]
## Issue Type

- [ ] Bug report
- [ ] Feature request
- [x] Question / support request
- [ ] Other

## Description

I tested a component using react-medium-image-zoom with Jest and got the following error in that module.
Do you have a solution?

```bash
  ● test ExampleDiv › When passing an image URL starting with https, it should be displayed.

    TypeError: img.decode is not a function

       6 |       "https://github.blog/wp-content/uploads/2023/05/1200.630-Community-wLogo.png";
       7 |
    >  8 |     render(<ExampleDiv imageUrl={imageUrl} />);
         |     ^
       9 |     expect(screen.getByRole("img")).toBeInTheDocument();
      10 |   });
      11 |

      at ControlledBase.handleImgLoad (node_modules/react-medium-image-zoom/dist/index.js:432:18)
      at ControlledBase.setAndTrackImg (node_modules/react-medium-image-zoom/dist/index.js:392:26)
      at ControlledBase.componentDidMount (node_modules/react-medium-image-zoom/dist/index.js:648:14)
      at commitLayoutEffectOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23310:28)
      at commitLayoutMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24688:9)
      at commitLayoutEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24674:7)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:24612:3)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26823:5)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at finishConcurrentRender (node_modules/react-dom/cjs/react-dom.development.js:25981:9)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25809:7)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:46:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:161:26)
      at render (node_modules/@testing-library/react/dist/pure.js:247:10)
      at Object.<anonymous> (src/components/image/__tests__/ExampleDiv.test.tsx:8:5)

  ● test ExampleDiv › When passing a local image address, it should be displayed.

    TypeError: img.decode is not a function

      21 |     const imagePath = "images/my-picture.jpg";
      22 |
    > 23 |     render(<ExampleDiv imageUrl={imagePath} />);
         |     ^
      24 |     expect(screen.getByRole("img")).toBeInTheDocument();
      25 |   });
      26 |

      at ControlledBase.handleImgLoad (node_modules/react-medium-image-zoom/dist/index.js:432:18)
      at ControlledBase.setAndTrackImg (node_modules/react-medium-image-zoom/dist/index.js:392:26)
      at ControlledBase.componentDidMount (node_modules/react-medium-image-zoom/dist/index.js:648:14)
      at commitLayoutEffectOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23310:28)
      at commitLayoutMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24688:9)
      at commitLayoutEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24674:7)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:24612:3)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:26823:5)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:26682:5)
      at finishConcurrentRender (node_modules/react-dom/cjs/react-dom.development.js:25981:9)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25809:7)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at act (node_modules/react/cjs/react.development.js:2582:11)
      at node_modules/@testing-library/react/dist/act-compat.js:46:25
      at renderRoot (node_modules/@testing-library/react/dist/pure.js:161:26)
      at render (node_modules/@testing-library/react/dist/pure.js:247:10)
      at Object.<anonymous> (src/components/image/__tests__/ExampleDiv.test.tsx:23:5)
```

my repository: https://github.com/amkkr/react-medium-image-zoom-test/blob/master/src/components/image/__tests__/ExampleDiv.test.tsx

**Comment by rpearce** [comment]
If you look at the last lines of https://github.com/rpearce/react-medium-image-zoom/blob/main/jest.setup.ts, you'll see a commented code block for telling JSDom (what Jest uses) how to handle the Image decode API that isn't implemented yet in the version you're using.

**Comment by amkkr** [comment]
Thanks for your response.
I have succeeded in getting my test code working!

https://github.com/amkkr/react-medium-image-zoom-test/blob/bb7862ae4e2473c9d3fac45e9011d07e45f73a98/tests/setupJest.ts#L1-L24

However, it is difficult to notice the comment in jest.setup.ts, so it would be great if you could describe it in other documents.

**Comment by rpearce** [comment]
I can include a note in the README, thanks.

**Comment by rpearce** [comment]
This is now in the README, and I added you to the "all contributors" section in the README for your helpful question!
