### ISSUE TITLE
Next.js App Router error: "Class Component being rendered in a Server Component"

### ISSUE THREAD

**Issue by karlhorky** [rpearce/react-medium-image-zoom#623]
## Description

First of all, thanks for `react-medium-image-zoom`, really useful! 🙌

Usage of `react-medium-image-zoom@5.2.5` in Next.js App Router (or other usage of React Server Component) without an intermediary Client Component causes the following error:

```
 ⨯ Class extends value undefined is not a constructor or null

This might be caused by a React Class Component being rendered in a Server Component, React Class Components only works in Client Components. Read more: https://nextjs.org/docs/messages/class-component-in-server-component
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-medium-image-zoom@5.2.5_react-dom@19.0.0-rc-6f23540c7d-20240528_react@19.0.0-rc-6f23540c7d-20240528/node_modules/react-medium-image-zoom/dist/index.js:404:65)
    at (rsc)/./node_modules/.pnpm/react-medium-image-zoom@5.2.5_react-dom@19.0.0-rc-6f23540c7d-20240528_react@19.0.0-rc-6f23540c7d-20240528/node_modules/react-medium-image-zoom/dist/index.js (/project/workspace/.next/server/vendor-chunks/react-medium-image-zoom@5.2.5_react-dom@19.0.0-rc-6f23540c7d-20240528_react@19.0.0-rc-6f23540c7d-20240528.js:20:1)
    at __webpack_require__ (/project/workspace/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./app/page.tsx:7:81)
    at (rsc)/./app/page.tsx (/project/workspace/.next/server/app/page.js:141:1)
    at Function.__webpack_require__ (/project/workspace/.next/server/webpack-runtime.js:33:42)
    at async e9 (/project/workspace/node_modules/.pnpm/next@15.0.0-canary.46_react-dom@19.0.0-rc-6f23540c7d-20240528_react@19.0.0-rc-6f23540c7d-20240528/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:483832)
    at async tb (/project/workspace/node_modules/.pnpm/next@15.0.0-canary.46_react-dom@19.0.0-rc-6f23540c7d-20240528_react@19.0.0-rc-6f23540c7d-20240528/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:487554)
    at async tS (/project/workspace/node_modules/.pnpm/next@15.0.0-canary.46_react-dom@19.0.0-rc-6f23540c7d-20240528_react@19.0.0-rc-6f23540c7d-20240528/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:488115)
    at async tS (/project/workspace/node_modules/.pnpm/next@15.0.0-canary.46_react-dom@19.0.0-rc-6f23540c7d-20240528_react@19.0.0-rc-6f23540c7d-20240528/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:488246)
    at async tj (/project/workspace/node_modules/.pnpm/next@15.0.0-canary.46_react-dom@19.0.0-rc-6f23540c7d-20240528_react@19.0.0-rc-6f23540c7d-20240528/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2138)
    at async /project/workspace/node_modules/.pnpm/next@15.0.0-canary.46_react-dom@19.0.0-rc-6f23540c7d-20240528_react@19.0.0-rc-6f23540c7d-20240528/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2793 {
  digest: '897794781'
}
 ⨯ node_modules/.pnpm/react-medium-image-zoom@5.2.5_react-dom@19.0.0-rc-6f23540c7d-20240528_react@19.0.0-rc-6f23540c7d-20240528/node_modules/react-medium-image-zoom/dist/index.js (397:30) @ eval
```

![Screenshot 2024-06-27 at 20 40 42](https://github.com/rpearce/react-medium-image-zoom/assets/1935696/790211bb-9b89-437b-b088-b5f27ecdee3b)

## Reproduction

Reproduction CodeSandbox: https://codesandbox.io/p/devbox/repro-react-medium-image-zoom-error-with-next-js-app-router-8v5drj?file=%2Fapp%2Fpage.tsx&workspaceId=7ecd71f9-9fcd-424c-8c4e-dfa4601f87d5

`app/page.tsx`

```tsx
import Zoom from "react-medium-image-zoom";

export default function Home() {
  return <Zoom zoomMargin={40}>abc</Zoom>;
}
```

It would be great if `'use client'` could be added to [`dist/index.js`](https://unpkg.com/browse/react-medium-image-zoom@5.2.5/dist/index.js), as is recommended with the advent of React Server Components.

This is to enable `react-medium-image-zoom` to work out of the box when imported into a Server Component. This will become a larger issue in future as more metaframeworks ship RSCs.

**Comment by karlhorky** [comment]
## Workaround

Use [`patch-package`](https://www.npmjs.com/package/patch-package) or [`pnpm patch`](https://pnpm.io/cli/patch) to add `'use client'` to the top of `node_modules/react-medium-image-zoom/dist/index.js`:

```diff
+'use client';
import React from 'react';
import ReactDOM from 'react-dom';

// ...
```

**Comment by rpearce** [comment]
Thanks for the info. I'll see what I can do and if the lib having use client makes sense.

**Comment by karlhorky** [comment]
Yeah I think adding `'use client'` is a backwards-compatible change: I haven't had issues with other non-Server Components usages of React with components with `'use client'` - the directive is just ignored.

**Comment by mulfyx** [comment]
https://nextjs.org/docs/app/building-your-application/rendering/composition-patterns#using-third-party-packages-and-providers

**Comment by yenes11** [comment]
creating wrapping with a client component and using that worked for me.

components/custom-zoom.tsx:

`
'use client';

import 'react-medium-image-zoom/dist/styles.css';
import Zoom from 'react-medium-image-zoom';
import { UncontrolledProps } from 'react-medium-image-zoom';

function CustomZoom(props: UncontrolledProps) {
  return <Zoom {...props} />;
}

export default CustomZoom;
`

app/page.tsx:

`
    <ThemedZoom>
        <img
          src={color.fabricColorImage}
          className="h-52 w-52 rounded object-cover"
        />
    </ThemedZoom>
`

**Comment by karlhorky** [comment]
> creating wrapping with a client component and using that worked for me

@yenes11 The point of this issue is to not require the extra intermediary Client Component - from the post at the top, ["without an intermediary Client Component"](https://github.com/rpearce/react-medium-image-zoom/issues/623#:~:text=React%20Server%20Component\)-,without%20an%20intermediary%20Client%20Component,-causes%20the%20following)

**Comment by rpearce** [comment]
I forgot about this issue. Given [`use client` is in the React docs](https://react.dev/reference/rsc/use-client), I'm open to adding this.

I haven't played with where to add it yet, but I wonder if simply adding it to https://github.com/rpearce/react-medium-image-zoom/blob/main/source/index.ts would get the job done 🤔

**Comment by karlhorky** [comment]
Every file exporting a Client Component using client features should have `'use client'` at the top.

So it should be a simple fix, yep! (as long as the directive does not get removed from the published file on npm)

**Comment by rpearce** [comment]
@karlhorky and anybody else: how does this look? https://github.com/rpearce/react-medium-image-zoom/pull/724

**Comment by karlhorky** [comment]
LGTM, added an approval over there 🙌

**Comment by karlhorky** [comment]
Thanks for the shoutout!

I can confirm that `react-medium-image-zoom@5.2.10` is compatible with React Server Components environments (eg. Next.js) now 🙌 

https://unpkg.com/browse/react-medium-image-zoom@5.2.10/dist/index.js

![Screenshot 2024-09-18 at 20 00 06](https://github.com/user-attachments/assets/6b67c310-1ad8-4cc4-9ded-6fa26207faea)
